name: small_kindness
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  flutter_hooks: ^0.21.2
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  build_runner: ^2.6.0
  toastification: ^3.0.3
  json_serializable: ^6.10.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
