// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9dE25EjuPymsJV2V-TKp6NKB8eT6H2AY',
    appId: '1:235090672511:web:3d6888fd6955cc74bbb84a',
    messagingSenderId: '235090672511',
    projectId: 'small-kindness-ac24d',
    authDomain: 'small-kindness-ac24d.firebaseapp.com',
    storageBucket: 'small-kindness-ac24d.firebasestorage.app',
    measurementId: 'G-JBMPR3S4KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ATQEvYotXgsodJ_vQJpN-DzisNUxO-M',
    appId: '1:235090672511:android:feaeac483d4a0eccbbb84a',
    messagingSenderId: '235090672511',
    projectId: 'small-kindness-ac24d',
    storageBucket: 'small-kindness-ac24d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfsrxILbL8wZ3Ix7DJq3u7-XcBB0miUP0',
    appId: '1:235090672511:ios:748f73cfa356483bbbb84a',
    messagingSenderId: '235090672511',
    projectId: 'small-kindness-ac24d',
    storageBucket: 'small-kindness-ac24d.firebasestorage.app',
    iosBundleId: 'com.example.smallKindness',
  );
}
